### ISSUE TITLE
1.16.5 doesn't tell us what origin we are when selecting "random"

### ISSUE THREAD

**Issue by SinumOfficial** [EdwinMindcraft/origins-architectury#114]
nothing happens when we select "random". We can tell we are _something_ but we have absolutely no idea what we are, because we didn't get the book. since it's 1.16.5, is there no more support for this version since it's a bit older?

**Comment by EdwinMindcraft** [comment]
1.16.5 is complicated...
Technically, most of the code I wrote for 1.17 and 1.18 would work on 1.16.5 if it were not for the fact that it uses features from java 11+. I'm currently focusing most of my efforts on 1.18 because that's the version that is targeted by fabric.

Also if you need to know your origin, just press "o", or whatever you rebinded the "View Origin" key to.
