### ISSUE TITLE
Prevent death priority

### ISSUE THREAD

**Issue by Ceifeire** [EdwinMindcraft/origins-architectury#220]
This may or may not be a mod compatibility. I have added Hardcore Revival with an origin that has a prevent death power. The revival mechanic triggers on death before the prevent death power triggers. and if the revival mechanic fails to save the player then the prevent death mechanic kicks in.

Is there a way to do this in the opposite order?

**Comment by EdwinMindcraft** [comment]
Yes, but not on my end. Basically what HR is doing is checking if any damage would be lethal, instead of performing the actions on death. Which works fine in the context of what they are trying to do, but not in a context where you're *supposed* to die.
TL;DR: I can't do anything since they are effectively preventing the death event from firing.
