### ISSUE TITLE
Keybinds not Working Correctly

### ISSUE THREAD

**Issue by QuantumXenon** [EdwinMindcraft/origins-architectury#235]
All powers use the same keybind (`g`), which makes origins with multiple active powers not work correctly.

**Comment by EdwinMindcraft** [comment]
It should be fixed since I found and corrected the error, but I haven't tested it yet.

**Comment by QuantumXenon** [comment]
Ok, great!

**Comment by QuantumXenon** [comment]
As far as I can tell, this was fixed in 1.5.0.6

**Comment by theohteo** [comment]
what if I can only use modded 1.18.2 minecraft and can't update it how am I going to play?

**Comment by BlackjackMKV** [comment]
> what if I can only use modded 1.18.2 minecraft and can't update it how am I going to play?

I agree with this. While ya'll definitely aren't obligated to, I would *love* to see a backport for 1.18.2 with this issue fixed since there isn't a build for 1.18.2 without this bug. Given the size of it and how popular 1.18.2 is as a version for modding, it would be greatly appreciated.

**Comment by BlackjackMKV** [comment]
And, to clarify, I'm not asking for ongoing support for 1.18.2. I don't expect anyone to support an out of date version, of course. Rather, this bug is just massively debilitating to the point that I would love to see at least a single version released for 1.18.2 to fix it. There are a LOT of mods that haven't updated past 1.18.2, which means that a lot of people like my friend group don't have the option to simply update to 1.19+, on top of the many questionable decisions Mojang is making in 1.19.1+ onwards(such as the report system) making it generally not a great idea for even vanilla users to update. Basically, lots of users either can't because of mod issues or won't because of Mojang doing dumb things, and therefore I feel like just one update to fix this issue would be extremely well received.
