### ISSUE TITLE
Can’t Join World because of "Invalid Player Data"

### ISSUE THREAD

**Issue by QuantumXenon** [EdwinMindcraft/origins-architectury#236]
Crash Log: https://pastebin.com/xbDy1DnV

_Origins (Forge) 1.5.0.5, Forge 43.1.1, Minecraft 1.19.2_

**Comment by EdwinMindcraft** [comment]
I'll admit I have legitimately not a single clue of how that error could possibly happen in normal gameplay.
FYI for this to happen, it would mean that the datasync event is called on the client (which doesn't happen) before the server managed to synchronize even once (which is basically the first thing that happens when you boot a world).
The only other option is that for some reason the registry initialization would've failed, and that would just flat out crash the game on boot.

**Comment by QuantumXenon** [comment]
Sorry if I wasn’t clear, the crash happens immediately upon trying to join a world

**Comment by EdwinMindcraft** [comment]
I added additional network safety code, and properly cleaned up registries when leaving a world, but I can't be sure it'll work properly.

**Comment by QuantumXenon** [comment]
Ok, great!

**Comment by QuantumXenon** [comment]
@EdwinMindcraft The issue still seems to be a problem in 1.5.0.6. The way I can reproduce it the most reliably is:
- Join a world
- Leave the world to the title screen
- Try to join the world again -> I get the error message here

**Comment by blacksabin** [comment]
I too, am encountering this issue. I'm using [Origins++](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus) and I can _sometimes_  hop back into the world. Singleplayer.

**Comment by MrBOOMberMAN** [comment]
same here, when this will be fixed?
