### ISSUE TITLE
1.19 1.5.0.4 Night Vision Flickering

### ISSUE THREAD

**Issue by Thisguyneedshelp** [EdwinMindcraft/origins-architectury#241]
Hello on every instance of the mod i run, the night vision power flickers on and off constantly.

**Comment by Thisguyneedshelp** [comment]
it also seems like no datapacks in general are working

**Comment by Thisguyneedshelp** [comment]
also probably part of these issues is i frequently cant load into a world and get the error message resource root power missing or something along those lines

**Comment by Thisguyneedshelp** [comment]
hey ive tried out the 1.19.2 version and it doesnt seem to have the problems that im experiencing so i was wondering if youd just try backporting 1.5.0.6 to 1.19 i think thatd work

**Comment by EdwinMindcraft** [comment]
Short answer: No.
Long answer: The changes mojang did for 1.19.1 & 1.19.2 are minimal (I had to change 1 method call over the entire codebase), most mods can and have updated, if you don't want chat reporting, have it be disabled on the server, or use mods/plugins that do the job. The changes forge did however, are required since they fixed Jar-in-Jar (which origins relies on since 1.5.0.1) in 1.19.1, as such Origins **cannot** be backported prior to 1.19.1, and since that version had a flaw critical enough to be hotfixed, there is no good reason not to use 1.19.2.
