### ISSUE TITLE
Crash on first load

### ISSUE THREAD

**Issue by ItoKyoshiro** [EdwinMindcraft/origins-architectury#278]
Hi!
Not so sure how to report (didn't find any template) but I get a crash always on the first usage of a skill of an origin, with the basic and with customs.
After this, I don't have the issue anymore but if I modify files and do /reload I got the same crash.

version: 1.18.2 - 1.5.0.1

[crash-2022-12-05_15.18.49-client.txt](https://github.com/EdwinMindcraft/origins-architectury/files/10160470/crash-2022-12-05_15.18.49-client.txt)

Also, can corroborate that this report happens if you have no selected origin (of after using the command with origin:empty) where I got invulnerability against an skeleton (arrows got deflected) even after I used the command for selecting origin, or with the orb)
https://github.com/EdwinMindcraft/origins-architectury/issues/267

Not sure on this one, but also encountered the issue with the monkey addon that I couldn't climb trees nor phase through leaves (not sure if on the datapack end or on the functionality here)
https://www.curseforge.com/minecraft/customization/monkey-origin

**Comment by ChrysanthCow** [comment]
This bug has already been fixed on 1.19.2 for a future release in 1.7.0.1, as that accounts for the power usage packet not receiving a correct value due to certain powers not being loaded at the time.

I may get around to fixing 1.18.2 at a later date, I'm just uncertain on when/if I'll get around to it.
