### ISSUE TITLE
Joining Server

### ISSUE THREAD

**Issue by f0kx** [EdwinMindcraft/origins-architectury#284]
![image](https://user-images.githubusercontent.com/14795020/209857086-ef435386-7ba2-40e7-9506-974a60a5aedd.png)
 
Whenever i want to join server this will happens? What is that? i cant join after this

**Comment by EdwinMindcraft** [comment]
Don't join a non-origins server with origins.

**Comment by f0kx** [comment]
Lol do you think iam stupid ? It’s my own server and origin is on it…maybe ask before and than close it but thx for nothing 👎🏻

**Comment by EdwinMindcraft** [comment]
Okay, it can be 4 things:
- A version mismatch: Use the same version on the client and the server.
- You're using the 1.5.* builds for 1.18.2, but it doesn't work because forge is broken.
- You're using a non-standard server jar.
- You have a mod that breaks.

The only thing I have control over would be the 1.5 version, and you'd have found a workaround if you checked the pinned issues.
