### ISSUE TITLE
no 1.19.4

### ISSUE THREAD

**Issue by TeriblTylr** [EdwinMindcraft/origins-architectury#384]
why is there no mod for 1.19.4?

**Comment by ChrysanthCow** [comment]
Simply put, I didn't feel a need to port to 1.19.4 as 1.20.1 was already out at the time of when we started moving away from 1.19.2 (which needed a lot of fixes, which explains why it took so long).

If we were to backtrack from 1.20.1, we'd basically have to remove features from that branch, and I just don't feel that 1.19.4 is really all that worthwhile of a version to backport to, as most modders and players would've moved onto 1.20. It's a very weird spot in mc's codebase, and a lot of modded players at the time stayed on 1.19.0-2 due to availability.
