### ISSUE TITLE
Immesive Portals make origins stop working

### ISSUE THREAD

**Issue by aDwCarrazzone** [EdwinMindcraft/origins-architectury#392]
Whenever you teleport to nether or other worlds the origins simply stops working... I'm using Minecraft 1.20.1, Forge 47.1.3, origins-forge-1.20.1-1.10.0.2-all.jar, and Sinytra: Connector-1.0.0-beta.21+1.20.1-full.jar

**Comment by aDwCarrazzone** [comment]
Help pls?

**Comment by ChrysanthCow** [comment]
Okay, so I don't think that we can fix this. Mainly because Immersive Portals is a Fabric mod (assuming you're loading it via Connector), and so it doesn't call the usual Forge events that we use to make sure that dimension swaps handle methods due to probably custom implementation of the dimension change code.
