### ISSUE TITLE
[1.20.1] Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_entity_condition] was missing

### ISSUE THREAD

**Issue by DSMister** [EdwinMindcraft/origins-architectury#416]
Version: origins-forge-1.20.1-1.10.0.5-all.jar
Forge: 47.2.20

I've been having this error pop up in my multiplayer server, causing us to be unable to join the server. It would take a few tries before I'm able to join again. I'm unsure about what's going on here.

For reference, I do have Medieval Origins Revival installed as well. I'm not sure if that could also lead to issues.

**Comment by muon-rw** [comment]
If you could, please see if the issue persists with:
- just Medieval Origins Revival and Origins Forge, and required dependencies
- keeping your existing mod list but removing Medieval Origins Revival

As well, please send the latest.log file from your logs folder after receiving the error.

**Comment by ChrysanthCow** [comment]
This is an issue with our registry system, and I'm unsure if it's fixable due to us having to work around Forge's registry system to make reloadable datapackable registries a thing.

Potentially in future versions of the mod when we make a jump to NeoForge, we'll rewrite this system to be more in line with vanilla registries, and it should be fixed there.

**Comment by ChrysanthCow** [comment]
I've managed to fix it by removing a line that removes the key from the registries map, and handling concurrency so content isn't missing.
