### ISSUE TITLE
Crash with Origins Minus, log spam

### ISSUE THREAD

**Issue by Vivid141** [EdwinMindcraft/origins-architectury#422]
**Description:**
When playing with Origins Minus and using the Hellspawn origin (which has the ability to burn enemies with unarmed attacks), using said unarmed attack on an entity causes my game to immediately freeze and then crash. The latest.log file becomes so long that I actually had to wait to look at it because my modlauncher was buffering, and uploading it to mclo.gs truncated the file at 25,000 lines. I have no idea how many lines it actually is, but the file is almost 32MB. In the mclo.gs, the error text starts at line 275 and continues _for over 20,000 lines_.

**How to Reproduce:**
I was playing this on a pack with other mods, but the crash still occurs with just the necessary ones. I downloaded the given versions of the mods below, launched up a world, and punched the nearest mob- I've tried with a skeleton and a rabbit so far, but given the nature of the crash I'm inclined to believe it will work with any mob and the logs are far too chunky for me to bother testing.

**Versions:**
- Minecraft: 1.20.1
- Forge: 47.2.0
- Origins: for Forge, 1.20.1-1.10.0.5
- Caelus API: 3.1.0+1.20
- Pehkui: 3.7.12+1.20.1-forge
- Related Datapacks: Origins Minus, version 2.1.1+1.19.3

**Log/s:**
- Latest.log on mclo.gs: https://mclo.gs/GxIsNWS

**Image/s:**
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/113260721/020d4b3d-4ef3-4832-a97f-53f63ae4f22b)

**Comment by ChrysanthCow** [comment]
Strange... will look into this soon.

**Comment by ChrysanthCow** [comment]
Okay, so this is a quirk with Origins Forge, that differs from Origins Fabric.
iirc, Edwin said that it would be kept this way with potentially a config option for the Fabric iteration behaviour, so I'm going to probably not change it, I'm going to handle this after asking Edwin what to do.

The Action On Hit power should not be used with the Damage action as it will loop indefinitely, as it triggers on any damage from you, rather than once like it does in Fabric.

**Comment by EdwinMindcraft** [comment]
Looking at the code, the fact that it crashes is a bug, as the author of Origins Minus has put in place [logic to prevent recursive calls](https://github.com/sisby-folk/origins-minus/blob/1.19/src/main/resources/data/origins_minus/powers/fire_punch.json#L50-L54), meaning that for some reason that logic fails.

If my understanding of the fabric logic is correct, here's how it works :
On-hit actions are only valid if the player actually takes damage, it works because when damage is only dealt when it's greater than the maximum damage taken during the immunity frames, meaning that at most the effects trigger twice.
A theoretical power dealing (damage+1) damage on hit would still crash the game the same way.

Our issue is that the hook forge provides is fired *before* the immunity gate is updated, which is why recursive powers crash on forge.

**Comment by ChrysanthCow** [comment]
Okay, I think I know how to fix this.

Because they use the old damage system in their code, we need to update the `origins:name` damage condition type to support the NameMutableDamageSource interface. Origins Fabric also doesn't do this, so I'll file a report over there.

**Comment by ChrysanthCow** [comment]
I've adjusted the logic that mimics the Fabric logic to actually mimic it, but left the above bug unfixed because that's for upstream to fix first.
