### ISSUE TITLE
The mod does not work with anti-cheat on the server!

### ISSUE THREAD

**Issue by ZendyGwendy** [EdwinMindcraft/origins-architectury#465]
How to fix this problem? Can you recommend an anti-cheat that the mod works with (if there is one)? Anti-cheat bans Avians for their smooth fall, for example, etc.

**Comment by ChrysanthCow** [comment]
Hi, I don't think anti-cheat will ever be compatible with the Origins mod, simply due to how many things Origins changes internally. Anti-cheat is designed around vanilla and cannot account for things introduced by the Origins mod.

If you're having problems with your players cheating on an Origins server, I'm unsure what to say other than try seeing if you can disable modules that would affect individual origins, if the anticheat is modular.
