### ISSUE TITLE
Unable to add modded foods to the meat tag for carnivore origins.

### ISSUE THREAD

**Issue by Biokoro** [EdwinMindcraft/origins-architectury#9]
Adding modded food items through a data pack doesn't seem to work. Whenever I use this data pack in game, it disables the diet system entirely. Any origin can eat any food regardless of dietary restrictions. I am unsure whether this is an issue with the data pack, or the mod itself. I have posted this same pack on the origins discord asking if it is structured correctly, and have yet to get a response.

(PS, apologies for anything not posted/formatted correctly, this is my first time using github)

[Carnivore Meat Tags.zip](https://github.com/EdwinMindcraft/origins-architectury/files/6424964/Carnivore.Meat.Tags.zip)
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/6424966/latest.log)
[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/6424967/debug.log)

**Comment by EdwinMindcraft** [comment]
According to your logs, loading the tag failed. (Latest L1320)
You are asking for the item farmersdelight:sheperds_pie, which doesn't exist.
I would recommend checking if the item exists, and if it does correct the name. otherwise, minecraft supports optional tags in the format, which would allow tag recognition to fail without ignoring the tag completely.
```json
{"id": "farmersdelight:sheperds_pie", "required": false}
```
If you can, check your logs for "Couldn't load item tag origins:meat as it is missing following references"
If after correcting this you still get a bug, please comment back on this issue and I'll try to track it down.

**Comment by Biokoro** [comment]
Yeah, that worked. To think a single letter would've ruined everything haha. I feel kinda dumb now realizing that the fix was so simple. Regardless, thanks for your help! It means a lot! This has been frustrating me for the past week.
